// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package helloworld is a generated protocol buffer package.

option go_package = "datingapp/pb";

It is generated from these files:
	messages.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	User
	ListUsersRequest
	ListUsersResponse
	ChatRequest
	ChatResponse
	HistoryRequest
	HistoryResponse
	ConnectRequest
	ConnectResponse
	MatchesRequest
	MatchesResponse
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type User struct {
	ID          int64   `protobuf:"varint,1,opt,name=iD" json:"iD,omitempty"`
	DisplayName string  `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty"`
	Matches     []int64 `protobuf:"varint,3,rep,packed,name=matches" json:"matches,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetMatches() []int64 {
	if m != nil {
		return m.Matches
	}
	return nil
}

type ListUsersRequest struct {
}

func (m *ListUsersRequest) Reset()                    { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()               {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ListUsersResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *ListUsersResponse) Reset()                    { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()               {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ChatRequest struct {
	Message          string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Sender           string `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	TimestampCreated int64  `protobuf:"varint,3,opt,name=timestamp_created,json=timestampCreated" json:"timestamp_created,omitempty"`
}

func (m *ChatRequest) Reset()                    { *m = ChatRequest{} }
func (m *ChatRequest) String() string            { return proto.CompactTextString(m) }
func (*ChatRequest) ProtoMessage()               {}
func (*ChatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChatRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ChatRequest) GetTimestampCreated() int64 {
	if m != nil {
		return m.TimestampCreated
	}
	return 0
}

type ChatResponse struct {
}

func (m *ChatResponse) Reset()                    { *m = ChatResponse{} }
func (m *ChatResponse) String() string            { return proto.CompactTextString(m) }
func (*ChatResponse) ProtoMessage()               {}
func (*ChatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type HistoryRequest struct {
}

func (m *HistoryRequest) Reset()                    { *m = HistoryRequest{} }
func (m *HistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*HistoryRequest) ProtoMessage()               {}
func (*HistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type HistoryResponse struct {
	ChatHistory []*ChatRequest `protobuf:"bytes,1,rep,name=chatHistory" json:"chatHistory,omitempty"`
}

func (m *HistoryResponse) Reset()                    { *m = HistoryResponse{} }
func (m *HistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*HistoryResponse) ProtoMessage()               {}
func (*HistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *HistoryResponse) GetChatHistory() []*ChatRequest {
	if m != nil {
		return m.ChatHistory
	}
	return nil
}

type ConnectRequest struct {
}

func (m *ConnectRequest) Reset()                    { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()               {}
func (*ConnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ConnectResponse struct {
}

func (m *ConnectResponse) Reset()                    { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string            { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()               {}
func (*ConnectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type MatchesRequest struct {
}

func (m *MatchesRequest) Reset()                    { *m = MatchesRequest{} }
func (m *MatchesRequest) String() string            { return proto.CompactTextString(m) }
func (*MatchesRequest) ProtoMessage()               {}
func (*MatchesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type MatchesResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *MatchesResponse) Reset()                    { *m = MatchesResponse{} }
func (m *MatchesResponse) String() string            { return proto.CompactTextString(m) }
func (*MatchesResponse) ProtoMessage()               {}
func (*MatchesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MatchesResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*User)(nil), "helloworld.User")
	proto.RegisterType((*ListUsersRequest)(nil), "helloworld.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "helloworld.ListUsersResponse")
	proto.RegisterType((*ChatRequest)(nil), "helloworld.ChatRequest")
	proto.RegisterType((*ChatResponse)(nil), "helloworld.ChatResponse")
	proto.RegisterType((*HistoryRequest)(nil), "helloworld.HistoryRequest")
	proto.RegisterType((*HistoryResponse)(nil), "helloworld.HistoryResponse")
	proto.RegisterType((*ConnectRequest)(nil), "helloworld.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "helloworld.ConnectResponse")
	proto.RegisterType((*MatchesRequest)(nil), "helloworld.MatchesRequest")
	proto.RegisterType((*MatchesResponse)(nil), "helloworld.MatchesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}

// Client API for DatingGame service

type DatingGameClient interface {
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	SendChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	ChatHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	// rpc Connect (ConnectRequest) returns (ConnectResponse) {}
	Matches(ctx context.Context, in *MatchesRequest, opts ...grpc.CallOption) (*MatchesResponse, error)
}

type datingGameClient struct {
	cc *grpc.ClientConn
}

func NewDatingGameClient(cc *grpc.ClientConn) DatingGameClient {
	return &datingGameClient{cc}
}

func (c *datingGameClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := grpc.Invoke(ctx, "/helloworld.DatingGame/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datingGameClient) SendChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	out := new(ChatResponse)
	err := grpc.Invoke(ctx, "/helloworld.DatingGame/SendChat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datingGameClient) ChatHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	out := new(HistoryResponse)
	err := grpc.Invoke(ctx, "/helloworld.DatingGame/ChatHistory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datingGameClient) Matches(ctx context.Context, in *MatchesRequest, opts ...grpc.CallOption) (*MatchesResponse, error) {
	out := new(MatchesResponse)
	err := grpc.Invoke(ctx, "/helloworld.DatingGame/Matches", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DatingGame service

type DatingGameServer interface {
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	SendChat(context.Context, *ChatRequest) (*ChatResponse, error)
	ChatHistory(context.Context, *HistoryRequest) (*HistoryResponse, error)
	// rpc Connect (ConnectRequest) returns (ConnectResponse) {}
	Matches(context.Context, *MatchesRequest) (*MatchesResponse, error)
}

func RegisterDatingGameServer(s *grpc.Server, srv DatingGameServer) {
	s.RegisterService(&_DatingGame_serviceDesc, srv)
}

func _DatingGame_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatingGameServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.DatingGame/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatingGameServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatingGame_SendChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatingGameServer).SendChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.DatingGame/SendChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatingGameServer).SendChat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatingGame_ChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatingGameServer).ChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.DatingGame/ChatHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatingGameServer).ChatHistory(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatingGame_Matches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatingGameServer).Matches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.DatingGame/Matches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatingGameServer).Matches(ctx, req.(*MatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatingGame_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.DatingGame",
	HandlerType: (*DatingGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _DatingGame_ListUsers_Handler,
		},
		{
			MethodName: "SendChat",
			Handler:    _DatingGame_SendChat_Handler,
		},
		{
			MethodName: "ChatHistory",
			Handler:    _DatingGame_ChatHistory_Handler,
		},
		{
			MethodName: "Matches",
			Handler:    _DatingGame_Matches_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}

// Client API for ClientChat service

type ClientChatClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
}

type clientChatClient struct {
	cc *grpc.ClientConn
}

func NewClientChatClient(cc *grpc.ClientConn) ClientChatClient {
	return &clientChatClient{cc}
}

func (c *clientChatClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	out := new(ChatResponse)
	err := grpc.Invoke(ctx, "/helloworld.ClientChat/Chat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClientChat service

type ClientChatServer interface {
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
}

func RegisterClientChatServer(s *grpc.Server, srv ClientChatServer) {
	s.RegisterService(&_ClientChat_serviceDesc, srv)
}

func _ClientChat_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientChatServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.ClientChat/Chat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientChatServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientChat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.ClientChat",
	HandlerType: (*ClientChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _ClientChat_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xb5, 0x2d, 0x37, 0x4e, 0x9e, 0x83, 0x3f, 0xe6, 0x90, 0x0a, 0xb5, 0x05, 0xb3, 0x87, 0x60,
	0x28, 0xf8, 0xe0, 0x9e, 0x42, 0xa0, 0x3d, 0xd8, 0x10, 0xa7, 0xa4, 0x3d, 0x28, 0xf4, 0x5c, 0xb6,
	0xd6, 0x10, 0x0b, 0xf4, 0x55, 0xed, 0x86, 0xa2, 0x9f, 0xd4, 0x7f, 0x59, 0x24, 0xad, 0x94, 0x55,
	0x1a, 0x1f, 0xda, 0x9b, 0xe7, 0xbd, 0xd9, 0xe7, 0x79, 0x6f, 0x06, 0x61, 0x12, 0xb3, 0x52, 0xf2,
	0x81, 0xd5, 0x2a, 0xcb, 0x53, 0x9d, 0x12, 0x0e, 0x1c, 0x45, 0xe9, 0xaf, 0x34, 0x8f, 0x02, 0x21,
	0x70, 0xbe, 0x2b, 0x2b, 0x9f, 0x7f, 0x3e, 0xb2, 0xd2, 0x44, 0x18, 0x26, 0x32, 0x66, 0xb7, 0xbf,
	0xe8, 0x2f, 0xcf, 0xfc, 0xea, 0xb7, 0xb8, 0x04, 0x4c, 0x4f, 0x16, 0x15, 0xe4, 0x62, 0x64, 0xf4,
	0x4c, 0x53, 0x53, 0x0a, 0x1f, 0xc3, 0x6f, 0x8a, 0x73, 0x9a, 0x60, 0x10, 0x6e, 0x2b, 0xd2, 0xf1,
	0x07, 0xe1, 0x96, 0x16, 0x18, 0x07, 0xa1, 0xca, 0x22, 0x59, 0x7c, 0x2d, 0xa5, 0x07, 0xd5, 0x2b,
	0x1b, 0xaa, 0x34, 0xa5, 0xde, 0x1f, 0x58, 0xb9, 0xce, 0xc2, 0x59, 0x3a, 0x7e, 0x53, 0x0a, 0xc2,
	0xec, 0x2e, 0x54, 0xba, 0xd4, 0x55, 0x66, 0x46, 0x71, 0x8d, 0xb9, 0x85, 0xa9, 0x2c, 0x4d, 0x14,
	0xd3, 0x25, 0x5e, 0x3d, 0x96, 0x80, 0xdb, 0x5f, 0x38, 0xcb, 0xf1, 0x7a, 0xb6, 0x7a, 0x32, 0xb9,
	0x2a, 0x3b, 0xfd, 0x9a, 0x16, 0x11, 0xc6, 0x9b, 0x83, 0xd4, 0x8d, 0xdf, 0xa3, 0x6e, 0xe8, 0x02,
	0x27, 0x8a, 0x93, 0x80, 0x73, 0x33, 0xb0, 0xa9, 0xe8, 0x3d, 0xe6, 0x3a, 0x8c, 0x59, 0x69, 0x19,
	0x67, 0xdf, 0xf7, 0x39, 0x4b, 0xcd, 0x81, 0xeb, 0x54, 0x66, 0x67, 0x2d, 0xb1, 0xa9, 0x71, 0x31,
	0xc1, 0x79, 0xfd, 0x6f, 0xf5, 0x94, 0x62, 0x86, 0xc9, 0x2e, 0x54, 0x3a, 0xcd, 0x8b, 0xc6, 0xcc,
	0x1d, 0xa6, 0x2d, 0x62, 0xac, 0x5c, 0x61, 0xbc, 0x3f, 0x48, 0x6d, 0x60, 0x63, 0xe8, 0xb5, 0x6d,
	0xc8, 0x72, 0xe0, 0xdb, 0xbd, 0xa5, 0xfe, 0x26, 0x4d, 0x12, 0xde, 0x37, 0xb4, 0x98, 0x63, 0xda,
	0x22, 0x4f, 0x43, 0x7c, 0xa9, 0xe3, 0x6d, 0x9a, 0xae, 0x30, 0x6d, 0x91, 0x7f, 0xcb, 0x73, 0x7d,
	0x8b, 0xd1, 0x4d, 0xce, 0xac, 0x39, 0xa7, 0x8f, 0x38, 0xbd, 0x97, 0x45, 0x75, 0x2a, 0xe4, 0xda,
	0xfd, 0xf6, 0x85, 0x79, 0x17, 0x2f, 0x30, 0x59, 0x54, 0x88, 0xde, 0xfa, 0xf7, 0x00, 0xd8, 0x4a,
	0x1d, 0x26, 0x0f, 0x37, 0xe5, 0x51, 0x7c, 0xc6, 0x59, 0xbb, 0x66, 0x7a, 0x6b, 0xbf, 0x7a, 0x7e,
	0x11, 0xde, 0xbb, 0x23, 0xac, 0x31, 0xdc, 0xa3, 0x4f, 0x38, 0xbd, 0xe7, 0x24, 0x28, 0x73, 0xa3,
	0x63, 0x49, 0x7a, 0xee, 0xdf, 0x44, 0x2b, 0xb0, 0xab, 0xcf, 0xc6, 0xe4, 0x4c, 0x5e, 0xc7, 0x44,
	0x67, 0xa3, 0xde, 0x9b, 0x17, 0xb9, 0x56, 0x69, 0x8b, 0x91, 0xc9, 0xba, 0xab, 0xd2, 0x5d, 0x49,
	0x57, 0xe5, 0xd9, 0x72, 0x44, 0x6f, 0x7d, 0x0b, 0x6c, 0xa2, 0x90, 0x13, 0x5d, 0x59, 0xba, 0xc6,
	0xf0, 0xbf, 0xad, 0xfd, 0x38, 0xa9, 0xbe, 0x0a, 0x1f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x45,
	0xaf, 0xc2, 0x51, 0x27, 0x04, 0x00, 0x00,
}
